services:
  - type: web
    name: licencias-construccion
    env: node
    region: oregon
    plan: free
    buildCommand: npm install && cd client && npm install && npm run build && cd ..
    startCommand: npm run server
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
